<?php
/**
 * Plugin Name: Oripa Ranking Manager
 * Description: Online Oripa ranking data manager.
 * Version: 1.1.0
 * Requires PHP: 8.2
 */
if (!defined('ABSPATH')) exit;
define('ORIPA_RANKING_VERSION','1.1.0');
add_action('init', function () {
 register_post_type('oripa_service',['labels'=>['name'=>'オリパサービス','singular_name'=>'オリパサービス','add_new_item'=>'オリパサービスを追加','edit_item'=>'オリパサービスを編集'],'public'=>true,'show_in_rest'=>true,'menu_icon'=>'dashicons-store','supports'=>['title','thumbnail'],'rewrite'=>['slug'=>'oripa-service']]);
 register_post_type('ranking_lp',['labels'=>['name'=>'ランキングLP','singular_name'=>'ランキングLP','add_new_item'=>'ランキングLPを追加','edit_item'=>'ランキングLPを編集'],'public'=>true,'show_in_rest'=>true,'menu_icon'=>'dashicons-chart-bar','supports'=>['title','thumbnail'],'rewrite'=>['slug'=>'ranking']]);
});
function oripa_meta($id,$key,$default=''){ $v=get_post_meta($id,$key,true); return $v === '' ? $default : $v; }
function oripa_field($key,$label,$value,$type='text'){ echo '<p><label><strong>'.esc_html($label).'</strong><br>'; if($type==='textarea'){echo '<textarea style="width:100%;min-height:70px" name="oripa_meta['.esc_attr($key).']">'.esc_textarea($value).'</textarea>';}else{echo '<input style="width:100%" type="'.esc_attr($type).'" name="oripa_meta['.esc_attr($key).']" value="'.esc_attr($value).'">';} echo '</label></p>'; }
function oripa_service_box($post){ $fields=['short_name'=>'短縮表記','logo'=>'ロゴURL','main_image'=>'メイン画像URL','description'=>'サービス説明','catch'=>'キャッチコピー','official_url'=>'公式サイトURL','asp_url'=>'共通ASP URL','google_url'=>'Google広告用URL','yahoo_url'=>'Yahoo広告用URL','meta_url'=>'Meta広告用URL','adnetwork_url'=>'アドネットワーク用URL','seo_url'=>'SEO流入用URL','tracking_params'=>'計測パラメータ','cta'=>'CTA文言','titles'=>'対応カードタイトル','company'=>'運営会社名','start_year'=>'サービス開始年','overall'=>'総合評価','beginner'=>'初心者向け評価','lineup'=>'ラインナップ評価','campaign'=>'キャンペーン評価','usability'=>'使いやすさ評価','shipping'=>'発送評価','support'=>'サポート評価','first_bonus'=>'初回特典','campaign_text'=>'キャンペーン内容','titles_handled'=>'取扱タイトル','min_price'=>'最低価格帯','tags'=>'特徴タグ','pros'=>'メリット（1行1項目）','cons'=>'デメリット（1行1項目）','points'=>'おすすめポイント（1行1項目）']; foreach($fields as $k=>$label){$type=in_array($k,['description','campaign_text','pros','cons','points'],true)?'textarea':($k==='start_year'?'number':'text');oripa_field($k,$label,oripa_meta($post->ID,$k),$type);} echo '<p><em>評価は0〜5、URLはhttps://から入力してください。</em></p>';wp_nonce_field('oripa_save','oripa_nonce');}
function oripa_lp_box($post){$fields=['seo_title'=>'SEOタイトル','meta_description'=>'メタディスクリプション','h1'=>'H1','intro'=>'導入文','fv_heading'=>'FV見出し','fv_sub'=>'FV補足文','ad_notice'=>'広告表記','editor'=>'監修・編集者情報','method'=>'ランキング調査方法','criteria'=>'比較基準','summary'=>'まとめ文','sticky_cta'=>'スマホ追従CTA文言','traffic_source'=>'流入媒体','sections'=>'表示セクション（カンマ区切り）','compare_fields'=>'比較項目（カンマ区切り）','ranking_services'=>'掲載サービスID（順位順・カンマ区切り）'];foreach($fields as $k=>$label){$type=in_array($k,['meta_description','intro','fv_sub','method','criteria','summary'],true)?'textarea':'text';oripa_field($k,$label,oripa_meta($post->ID,$k),$type);}echo '<p><strong>LP別上書き(JSON)</strong><br><textarea style="width:100%;min-height:100px" name="oripa_meta[overrides]">'.esc_textarea(oripa_meta($post->ID,'overrides','{}')).'</textarea></p>';wp_nonce_field('oripa_save','oripa_nonce');}
add_action('add_meta_boxes',function(){add_meta_box('oripa_service_data','サービス情報','oripa_service_box','oripa_service','normal','high');add_meta_box('oripa_lp_data','LP設定','oripa_lp_box','ranking_lp','normal','high');});
add_action('save_post',function($id){if(!isset($_POST['oripa_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['oripa_nonce'])),'oripa_save')||defined('DOING_AUTOSAVE')||!current_user_can('edit_post',$id))return;foreach((array)($_POST['oripa_meta']??[]) as $k=>$v){$k=sanitize_key($k);$v=is_array($v)?wp_json_encode($v,JSON_UNESCAPED_UNICODE):sanitize_textarea_field(wp_unslash($v));if(str_ends_with($k,'url'))$v=esc_url_raw($v);update_post_meta($id,$k,$v);}});
function oripa_services($lp){$ids=array_values(array_filter(array_map('absint',explode(',',oripa_meta($lp,'ranking_services')))));if(!$ids)$ids=get_posts(['post_type'=>'oripa_service','numberposts'=>-1,'orderby'=>'date','order'=>'ASC','fields'=>'ids']);return $ids;}
function oripa_url($id,$source){$map=['google'=>'google_url','yahoo'=>'yahoo_url','meta'=>'meta_url','adnetwork'=>'adnetwork_url','seo'=>'seo_url','asp'=>'asp_url'];return esc_url(oripa_meta($id,$map[$source]??'official_url',oripa_meta($id,'official_url')));}
function oripa_value($id,$key,$ov){return isset($ov[$id][$key])&&$ov[$id][$key]!==''?$ov[$id][$key]:oripa_meta($id,$key);}
function oripa_render_lp($lp){$source=sanitize_key($_GET['traffic']??oripa_meta($lp,'traffic_source','seo'));$ids=oripa_services($lp);$ov=json_decode(oripa_meta($lp,'overrides','{}'),true)?:[];ob_start();?><main class="oripa-lp" data-lp-id="<?php echo esc_attr($lp); ?>"><div class="oripa-ad"><?php echo esc_html(oripa_meta($lp,'ad_notice','本ページには広告が含まれます。')); ?></div><header class="oripa-hero"><h1><?php echo esc_html(oripa_meta($lp,'h1',get_the_title($lp))); ?></h1><p><?php echo esc_html(oripa_meta($lp,'intro')); ?></p><div class="oripa-top3"><?php foreach(array_slice($ids,0,3) as $i=>$id): ?><a class="oripa-top" href="<?php echo esc_url(oripa_url($id,$source)); ?>" data-service-id="<?php echo esc_attr($id); ?>" data-rank="<?php echo $i+1; ?>" data-cta-position="fv_top3" rel="sponsored nofollow"><?php echo esc_html(get_the_title($id)); ?></a><?php endforeach; ?></div></header><section class="oripa-ranking"><h2>おすすめランキング</h2><?php foreach($ids as $i=>$id):$rank=$i+1;?><article class="oripa-card rank-<?php echo $rank; ?>"><span class="oripa-rank"><?php echo $rank; ?>位</span><h3><?php echo esc_html(get_the_title($id)); ?></h3><p><?php echo esc_html(oripa_value($id,'description',$ov)); ?></p><p>総合評価 <?php echo esc_html(oripa_value($id,'overall',$ov)); ?>/5</p><a class="oripa-cta" href="<?php echo esc_url(oripa_url($id,$source)); ?>" data-service-id="<?php echo esc_attr($id); ?>" data-rank="<?php echo $rank; ?>" data-cta-position="ranking_card" rel="sponsored nofollow"><?php echo esc_html(oripa_value($id,'cta',$ov)?:'公式サイトを見る'); ?></a></article><?php endforeach;?></section><section class="oripa-table"><h2>比較表</h2><div class="oripa-scroll"><table><thead><tr><th>順位</th><th>サービス</th><th>総合評価</th><th>初心者向け</th><th>ラインナップ</th><th>初回特典</th><th>CTA</th></tr></thead><tbody><?php foreach($ids as $i=>$id):?><tr><td><?php echo $i+1;?></td><td><?php echo esc_html(get_the_title($id));?></td><td><?php echo esc_html(oripa_value($id,'overall',$ov));?></td><td><?php echo esc_html(oripa_value($id,'beginner',$ov));?></td><td><?php echo esc_html(oripa_value($id,'lineup',$ov));?></td><td><?php echo esc_html(oripa_value($id,'first_bonus',$ov));?></td><td><a href="<?php echo esc_url(oripa_url($id,$source));?>" data-service-id="<?php echo esc_attr($id);?>" data-rank="<?php echo $i+1;?>" data-cta-position="comparison_table" rel="sponsored nofollow">見る</a></td></tr><?php endforeach;?></tbody></table></div></section><section class="oripa-info"><h2>ランキング調査方法</h2><p><?php echo nl2br(esc_html(oripa_meta($lp,'method')));?></p><h2>まとめ</h2><p><?php echo nl2br(esc_html(oripa_meta($lp,'summary')));?></p></section><?php if(oripa_meta($lp,'sticky_cta')):?><div class="oripa-sticky"><a href="<?php echo esc_url(oripa_url($ids[0]??0,$source));?>" data-service-id="<?php echo esc_attr($ids[0]??0);?>" data-rank="1" data-cta-position="sticky" rel="sponsored nofollow"><?php echo esc_html(oripa_meta($lp,'sticky_cta'));?></a></div><?php endif;?></main><?php return ob_get_clean();}
add_shortcode('oripa_ranking_lp',fn($a)=>oripa_render_lp(absint($a['id']??get_the_ID())));
add_filter('the_content',fn($c)=>is_singular('ranking_lp')&&!is_admin()?oripa_render_lp(get_the_ID()):$c);
add_action('wp_enqueue_scripts',function(){if(is_singular('ranking_lp')){wp_enqueue_style('oripa-ranking',plugins_url('assets/oripa.css',__FILE__),[],ORIPA_RANKING_VERSION);wp_enqueue_script('oripa-ranking',plugins_url('assets/oripa.js',__FILE__),[],ORIPA_RANKING_VERSION,true);}});
add_action('wp_head',function(){if(!is_singular('ranking_lp'))return;$id=get_the_ID();echo '<meta name="description" content="'.esc_attr(oripa_meta($id,'meta_description')).'"><link rel="canonical" href="'.esc_url(get_permalink($id)).'">';$items=[];foreach(oripa_services($id) as $i=>$sid)$items[]=['@type'=>'ListItem','position'=>$i+1,'name'=>get_the_title($sid)];echo '<script type="application/ld+json">'.wp_json_encode(['@context'=>'https://schema.org','@type'=>'ItemList','itemListElement'=>$items],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).'</script>';});
register_activation_hook(__FILE__,function(){flush_rewrite_rules();$names=['オリパワン','日本トレカセンター','ドーパ','エクストレカ','オリくじ'];$ids=[];foreach($names as $n){$found=get_posts(['post_type'=>'oripa_service','title'=>$n,'post_status'=>'any','numberposts'=>1,'fields'=>'ids']);$sid=$found[0]??wp_insert_post(['post_type'=>'oripa_service','post_status'=>'publish','post_title'=>$n]);$ids[]=$sid;foreach(['official_url'=>'https://example.com/','asp_url'=>'https://example.com/asp','seo_url'=>'https://example.com/seo','cta'=>'公式サイトを見る','description'=>$n.'のダミーサービス説明です。','catch'=>'初心者にも選びやすいサービス','overall'=>'4.5','beginner'=>'4.5','lineup'=>'4.0','campaign'=>'4.0','usability'=>'4.2','shipping'=>'4.0','support'=>'4.0','first_bonus'=>'初回限定キャンペーン'] as $k=>$v)update_post_meta($sid,$k,$v);}if(!get_page_by_path('online-oripa-ranking','ranking_lp')){$lp=wp_insert_post(['post_type'=>'ranking_lp','post_status'=>'publish','post_title'=>'オンラインオリパおすすめランキング']);update_post_meta($lp,'ranking_services',implode(',',$ids));update_post_meta($lp,'h1','オンラインオリパおすすめランキング');update_post_meta($lp,'ad_notice','本ページには広告が含まれます。');update_post_meta($lp,'method','公式情報・使いやすさ・ラインナップ・キャンペーン・発送・サポートを総合比較しています。');}});
register_deactivation_hook(__FILE__,fn()=>flush_rewrite_rules());

